// Copyright (c) 2018 RocketChicken Interactive Inc.

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

using Motive.Core.Json;
using Motive.Core.Scripting;
using Motive.Core.Globalization;
using Motive.Core.Models;
using Motive.Core.Media;
using JsonFx.Json;

namespace Motive.Gaming.Models
{
    /// <summary>
    /// A baked-in response to a character message.
    /// </summary>
    public class CharacterMessageResponse : TextMediaResponse
    {

    }

    /// <summary>
    /// A message from a character.
    /// </summary>
    public class CharacterMessage : TextMediaContent
    {
        public LocalizedMedia LocalizedImage { get; set; }
        public ObjectReference<Character> CharacterReference { get; set; }
        public CharacterMessageResponse[] Responses { get; set; }

        [JsonIgnore]
        public Character Character
        {
            get
            {
                if (CharacterReference != null)
                {
                    return CharacterReference.Object;
                }

                return null;
            }
        }

        public string ImageUrl
        {
            get
            {
                return LocalizedMedia.GetMediaUrl(LocalizedImage);
            }
        }

        public CharacterMessage()
        {
        }

        public override void GetMediaItems(IList<MediaItem> items)
        {
            LocalizedMedia.GetMediaItems(LocalizedImage, items);

            if (Responses != null)
            {
                foreach (var response in Responses)
                {
                    response.GetMediaItems(items);
                }
            }

            base.GetMediaItems(items);
        }
    }
}